composer.json

[Composer] Allow egeloen/json-builder 1.0.*

---

Form/Type/CKEditorType.php

[Form][Type] Add BC layer for setDefaultOptions

---

.travis.yml

[Travis] Remove SYMFONY_PHPUNIT_BRIDGE_VERSION + Add Symfony 3.1.*@dev

---

.coveralls.yml
.gitignore
.scrutinizer.yml
.travis.yml
README.md
Resources/bin/ckeditor-sync.sh
composer.json
phpunit.xml.dist

Remove coveralls in favor of scrutinizer

---

Form/Type/CKEditorType.php
Tests/DependencyInjection/AbstractIvoryCKEditorExtensionTest.php
Tests/Fixtures/config/Yaml/custom_paths.yml
Tests/Form/Type/CKEditorTypeTest.php

This PR fixes #221 by making the base path tralling slash optional.

Make trailling slash optional for base path

---

Resources/doc/index.rst

[Doc] Refine code block according to Symfony version

---

DependencyInjection/Configuration.php
DependencyInjection/IvoryCKEditorExtension.php
Form/Type/CKEditorType.php
Resources/doc/usage/index.rst
Resources/doc/usage/loading.rst
Resources/doc/usage/require-js.rst
Resources/views/Form/_ckeditor_javascript.html.php
Resources/views/Form/ckeditor_widget.html.twig
Tests/DependencyInjection/AbstractIvoryCKEditorExtensionTest.php
Tests/Fixtures/config/Yaml/require_js.yml
Tests/Form/Type/CKEditorTypeTest.php
Tests/Template/AbstractTemplateTest.php

This PR fixes #232 by adding tests and docs.

RequireJS support

---

Resources/doc/usage/append-javascript.rst
Resources/doc/usage/index.rst
Resources/views/Form/_ckeditor_javascript.html.php

This PR fixes #223 and #215 by explaining how append custom javascript in the default template.

[Doc] Add section about template overriding

---

Resources/doc/usage/template.rst

This error was reported in the [doc build errors page](http://symfony.com/doc/build_errors) on symfony.com

Fixed a minor syntax issue

---

Renderer/CKEditorRenderer.php
Tests/Renderer/CKEditorRendererTest.php

Fix usage of deprecated routing feature

---

Renderer/CKEditorRenderer.php
Tests/Renderer/CKEditorRendererTest.php
Tests/Template/AbstractTemplateTest.php

Properly destroy CKEditor instances

---

.travis.yml

[Travis] Upgrade matrix

---

Resources/doc/usage/skin.rst

This PR fixes #263 by improving/fixing the skin doc.

[Doc] Improve skin

---

.env.dist
.gitattributes
.travis.yml
Resources/doc/docker.rst
docker-compose.yml
docker/config/xdebug.ini
docker/hhvm/Dockerfile
docker/hhvm/config/xdebug.ini
docker/hhvm/entrypoint.sh
docker/php/Dockerfile
docker/php/config/xdebug.ini
docker/php/entrypoint.sh
travis/install.sh
travis/script.sh
travis/success.sh

This PR adds an hhvm container in order to more easily debug hhvm related issues and it also refactors travis scripts in order to add a docker build.

[Docker] Add hhvm container

---

travis/install.sh

[Travis] Replace sed by conmposer config

---

Resources/doc/usage/config.rst

This PR fixes #281 by improving a little bit the config doc.
@bruno-ds WDYT?

[Doc] Improve config documentation

---

.travis.yml

[Travis] Rely on trusty dist to make hhvm installable

---

Tests/AbstractTestCase.php
Tests/Command/CKEditorInstallerCommandTest.php
Tests/Installer/CKEditorInstallerTest.php
Tests/Model/ConfigManagerTest.php
Tests/autoload.php
composer.json
docker/hhvm/Dockerfile
phpunit.xml.dist
travis/script.sh

[Tests] Bump PHPUnit to 6.x

---

.scrutinizer.yml
.travis.yml

[Travis] Add missing Symfony versions

---

Command/CKEditorInstallerCommand.php
Installer/CKEditorInstaller.php
Resources/doc/usage/ckeditor.rst
Tests/Installer/CKEditorInstallerTest.php

[Installer] Add proxy support + Rely on options resolver
